switch to supervisord
silvio/docker-matrix pull request #17
Opened 2016-12-13 17:58 UTC by holzgeist

Similar reasons as in [https://github.com/silvio/matrix-riot-docker/pull/4](https://github.com/silvio/matrix-riot-docker/pull/4), but with multiple processes.

The turnserver is started depending on the presence of /data/turnserver.conf

2017-01-06 18:51 UTC, silvio requested changes
My comments and please rebase.

BTW, Thanks for your contribution!

2017-01-06 18:51 UTC, silvio commented on Dockerfile
> +COPY adds/turnserver.conf /conf/
Can you reneame this two files? Something like `supervisor-....conf`

2017-01-06 18:51 UTC, silvio commented on adds/start.sh
> +			fi
`turnserver.conf.deactivated`?
You probably mixed the conf files of supervisor and turnserver?

2017-01-06 18:51 UTC, silvio commented on adds/supervisord.conf
> +files = conf/*.conf
I don't know supervisior. The messages produced by turnserver and matrix are printed onto console with supervisor?

2017-01-20 09:49 UTC, xsteadfastx commented on adds/start.sh
> +			fi
i think its the supervisord config file for turnserver. if there is no `/data/turnserver.conf` then deactivate turnserver in supervisord... and if there is `/data/turnserver.conf` and the turnserver supervisord conf is deactivated... activate it with moving the file.

2017-01-20 09:51 UTC, xsteadfastx commented on adds/supervisord.conf
> +files = conf/*.conf
i dont know the defaults... but usually you add

```
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
```
to `supervisord.conf`.

2017-01-20 09:53 UTC, xsteadfastx commented
i really would love to see this merged. i think its a good way to get synapse and turn running. and it would make it easier to run both with a other user than root. supervisord supports `user = nobody` in the program config files.

2017-01-23 08:07 UTC, holzgeist commented
Sorry for the late reply. I'm in the end phase of my studies and therefore slightly stressed.

Thanks for the comments, I applied them and pushed.
However, I do not have a lot of experiences with github pull requests, so I don't know if that's enough or there is some button to push?

2017-01-23 08:23 UTC, silvio commented
Thanks @holzgeist , I will test you contribution. But this needs time.

2017-01-23 08:25 UTC, holzgeist commented
Do not test yet, I tested the actual run too late and found an error in the configuration..

the stdout_logfile et al. should be in [program:x] sections and not in [supervisor]. Rebuilding right now and pushing the result on success

2017-01-23 10:28 UTC, xsteadfastx commented
ok. now i was a few minutes too late :) i wanted to see supervisor in the image and did the changes @silvio wanted to see...plus added a user to run the services with and also fixed a bug with logging.

2017-01-23 15:39 UTC, holzgeist commented
@silvio: use pull-request #21, I have some troubles getting the log output from both matrix and turnserver to stdout.. 
The extra user is an additional benefit

2017-01-23 15:39 UTC, closed without merging